### ISSUE TITLE
blockchain.estimateFee(target) still has the same issue

### ISSUE THREAD

**Issue by aldrinzigmundv** [LtbLightning/bdk-flutter#102]
This was mentioned in Issue bitcoindevkit/bdk#58, but I've tried using it in the latest version. Unfortunately, the function still consistently returns 1.0, regardless of the target, far from the current fee rate of the blockchain.

**Comment by BitcoinZavior** [comment]
For fees, its best to call the blockchain api directly, each blockchain provides a api for fees.
Here is an example for rust using different blockchains:  https://github.com/bitcoindevkit/bdk/issues/1053
