### ISSUE TITLE
bdk-flutter in pure dart

### ISSUE THREAD

**Issue by aniketambore** [LtbLightning/bdk-flutter#11]
Hello,

I've a question out of curiosity as I can see the core methods is actually written in rust and binded with dart using `flutter_rust_bridge`. 

My question is, what's stopping us from developing the complete `bdk-flutter` package using pure dart?

**Comment by MrUnfunny** [comment]
Hey @aniketambore, Wouldn't this mean rewriting entire bdk logic in flutter? Given that we don't have any reliable core Bitcoin package in flutter, it's going to be even more challenging.

**Comment by aniketambore** [comment]
It will be more challenging though, but I think most of the algorithms for implementing bdk logic in pure dart are already created and available in pub. 

So it would be a good support and reference guide for writing entire `bdk-flutter` in pure dart (correct me if I'm wrong).

**Comment by MrUnfunny** [comment]
I'm currently just learning about bitcoin and don't have much experience but I don't think there is any reliable bitcoin core package on pub. The closest that I could find is [bitcoin_flutter](https://pub.dev/packages/bitcoin_flutter) but it is very outdated. There is another updated fork of the same package, [coinslib](https://pub.dev/packages/coinslib) but I had some issues with this too. So, IMO we'll first need a core bitcoin package in dart.

**Comment by aniketambore** [comment]
What I mean by algorithms is not already implemented bitcoin packages, but the core cryptographic or bips which is implemented in pure dart such as [secp256k1](https://pub.dev/packages/secp256k1), [ECDSA](https://pub.dev/packages/ecdsa), [Big & Little Endian](https://pub.dev/packages/encode_endian), [DER Signature](https://pub.dev/packages/dart_bip66), [Base58](https://pub.dev/packages/fast_base58), [Bech32](https://pub.dev/packages/bech32), [ripemd160](https://pub.dev/packages/pointycastle), etc...

Also I think we cannot call `bitcoin_flutter` outdated because it really has most of the concepts in place, but there are actually lots of version solving failed error because of its unsound null safety (maybe). But the library itself is great reference guide.

**Comment by BitcoinZavior** [comment]
Rewriting bdk in Dart or writing a package similar to bdk in Dart will be a huge task, the key objective of using BDK in bdk-flutter is to leverage the effort already spent in building BDK and also to take advantage of the robust nature of BDK as it's been tested numerous times.

bdk-flutter utilises rust bdk as its core library similar to how node js modules utilise c and c++ code as the core. It's a very common architecture for creating reusable modules and packages.

**Comment by aniketambore** [comment]
Okay, that sounds great to me. Thank you for your work on this!

**Comment by MrUnfunny** [comment]
Hey @BitcoinZavior, Is there any specific reason why you wrote rust code by yourself instead of using bdk-ffi like bak-swift and bdk-kotlin? Was it to change API to match your needs or is there some problem with integrating bdk-ffi?

**Comment by i5hi** [comment]
@MrUnfunny bdk-swift and bdk-kotlin will not give you c-bindings that are easily compatible with flutter.

As of today, this library is much closer to the actual bdk api and it will be getting closer moving forward.

**Comment by BitcoinZavior** [comment]
Thansk @i5hi
