### ISSUE TITLE
Unable to download bdk zip file 

### ISSUE THREAD

**Issue by sagarsubedi** [LtbLightning/bdk-flutter#123]
I am trying to build my app but I keep getting error 

>   CMake Error at CMakeLists.txt:28 (message):
    Download failed: 22;"HTTP response code said error"
    
   

Here is the URL i printed from the CMake file: `https://github.com/LtbLightning/test-pub/releases/download/0.29.3/bdk.0.29.3.zip`
I have the latest version of bdk-flutter 

Any insights? Thanks.

**Comment by BitcoinZavior** [comment]
Yes, I see the problem
In the meantime can you use "flutter pub add bdk-flutter" to install bdk-flutter please
