### ISSUE TITLE
signTransaction does not return signed PSBT.

### ISSUE THREAD

**Issue by MrUnfunny** [LtbLightning/bdk-flutter#14]
Hi @BitcoinZavior
Thanks for your work on this project. signTransaction is a void function. It takes input of a PSBT but does not return signed PSBT. Is this the intended behaviour? I think it needs to return a signed PSBT.

**Comment by MrUnfunny** [comment]
bdk signs and updates the PSBT that it gets as input to the sign method but it isn't possible in dart as it does not support pass by reference arguments. So, we explicitly need to return the signed PSBT. Please let me know if I am mistaken.

**Comment by BitcoinZavior** [comment]
Hey, @MrUnfunny yes you are right.
Currently creating PSBT can be one method and then sign+broadcast can be another method.

**Comment by BitcoinZavior** [comment]
This should be possible as part of changes for https://github.com/LtbLightning/bdk-flutter/issues/16

**Comment by BitcoinZavior** [comment]
@MrUnfunny you should be able to get a signed psbt from signTx() now. Let me know if it works for you else reopen this issue. Thanks!
