### ISSUE TITLE
Support for AGP 8.0.0 and above

### ISSUE THREAD

**Issue by M4dhav** [LtbLightning/bdk-flutter#142]
I recently encountered a problem where if I use any Gradle Distribution above 8.0.0, the build continuously fails with the message: 

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':bdk_flutter'.
 Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
    Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
 Run with --stacktrace option to get the stack trace.
 Run with --info or --debug option to get more log output.
 Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).

I believe the fix itself is simple enough, and a namespace needs to be added to the build.gradle file

**Comment by M4dhav** [comment]
I've already forked the project and solved the issue on my fork, lmk which branch to target and I'll open a PR

**Comment by BitcoinZavior** [comment]
Hi @M4dhav Thanks for your interest and also the possible solution.
Please open PR for `main` branch.

**Comment by M4dhav** [comment]
Okay, submitted

**Comment by Saleciani** [comment]
could this be related to 

```
* What went wrong:
Execution failed for task ':bdk_flutter:parseReleaseLocalResources'.
> A build operation failed.
      java.nio.file.NoSuchFileException: /Users/joaolobo/.gradle/caches/transforms-3/7acf09211b2ddac30391e0bc8a091ce2/results.bin
   > java.nio.file.NoSuchFileException: /Users/joaolobo/.gradle/caches/transforms-3/7acf09211b2ddac30391e0bc8a091ce2/results.bin

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

```

this error?
