### ISSUE TITLE
Requirements for Stackmate to migrate to bdk-flutter

### ISSUE THREAD

**Issue by i5hi** [LtbLightning/bdk-flutter#27]
hey!

Awesome work man!

We have been using bdk via ffi in our mobile wallet for nearly a year now and seeing the maturity of bdk-flutter we have decided to start the process of migration to minimise how many repos we have to maintain.

There are a few missing pieces that we need bdk-flutter to support for us to completely make the move. 

The main requirements we have are 

- [ ] Support for multiple wallets:

FWIU, only a single wallet is supported at the moment. 

Looking at the api, I notice that there is a createWallet() function - which can internally create a `label` using `bdk::wallet::wallet_name_from_descriptor` and create the sqlite db accordingly. `label` will be returned as part of the response. 

This `label` can then be used with wallet commands to support multiple wallets. 

- [ ] Purge wallet db

If multiple wallets are being supported, there should be an option to purge a wallet's sqlite db.
 
- [ ] Sweep wallet

This should not be much, a new fn called `sweepFunds` can be created for this. This could be a good first issue for me to get the hang of the entire end to end FFI workflow. 

If you have any documentation on this process, that would be really helpful or if you could give me a run down either here or if we can schedule a call over discord that would be even better. I will document the process so that new developers will find it easy to contribute.

A list of all our requirements are here but the above two are critical for us to migrate immediately. 

https://github.com/StackmateNetwork/the-stackmate/issues/77

**Comment by BullishNode** [comment]
Support for multiple Bitcoin Wallets also a requirement for Bull Bitcoin, fyi

**Comment by BitcoinZavior** [comment]
@i5hi @BullishNode 
Thanks for the confidence and for the feature request.

Multiple wallet instances will be supported shortly, we should have a PR for this in a week or so.

Purge and sweep are good to have and can be done.

**Comment by BitcoinZavior** [comment]
https://github.com/LtbLightning/bdk-flutter/pull/39 addresses multiple wallets. Purge and Sweep have their own issue numbers #28 and #29

**Comment by i5hi** [comment]
Thanks @BitcoinZavior.

I just got email notifications of messages you have sent me over discord. 

I am currently locked out of my discord since I do not have access to my 2fa device. I will be back on the 15th.
