### ISSUE TITLE
pub.dev static analysis

### ISSUE THREAD

**Issue by BitcoinZavior** [LtbLightning/bdk-flutter#42]
Address static analysis issues identified by pup.dev.
Issues mentioned under the “Pass Static Analysis” section: https://pub.dev/packages/bdk_flutter/score and see what we can do about the

**Comment by MrUnfunny** [comment]
This should be solved by excluding files generated folder from [analysis file](https://github.com/LtbLightning/bdk-flutter/blob/main/analysis_options.yaml)

**Comment by BitcoinZavior** [comment]
Thanks @MrUnfunny 👍
