### ISSUE TITLE
Descriptor, descriptorSecretKey / secretKey name and type mismatch

### ISSUE THREAD

**Issue by danielnordh** [LtbLightning/bdk-flutter#47]
Name and type mismatch when creating a descriptor.
The `secretKey` parameter of `Descriptor.newBip84` expects `String`, not `DescriptorSecretKey`:

```dart
final descriptorSecretKey = await DescriptorSecretKey.create(
      network: Network.Testnet,
      mnemonic: mnemonic);
final descriptor = await Descriptor.newBip84(
      secretKey: descriptorSecretKey,
      network: Network.Testnet,
      keyChainKind: KeychainKind.External);
```

Some of the descriptor templates also has the parameter named `secretKey`, while others use `descriptorSecretKey`.
Bip44 works as expected, the others do not.

**Expected**
Parameter called `descriptorSecretKey` always, accepting `DescriptorSecretKey` type always

**Comment by BitcoinZavior** [comment]
Will have a patch shortly, thanks for looking into it.
