### ISSUE TITLE
.toString() methods of Mnemonic and Descriptor return objects, not strings

### ISSUE THREAD

**Issue by danielnordh** [LtbLightning/bdk-flutter#51]
Using `Mnemonic.toString()` and `Descriptor.toString()` doesn't work as they both return objects instead of Strings.

Example with Mnemonic:

```dart
Mnemonic.create(WordCount.Words12).then((mnemonic) {
   final mstring = mnemonic.toString(); // This is still "Instance of 'Mnemonic'", not the mnemonic as String
});
```

**Comment by danielnordh** [comment]
Solved by using `.asString()` instead.

**Comment by BitcoinZavior** [comment]
Added issue to track this https://github.com/LtbLightning/bdk-flutter/issues/53
