### ISSUE TITLE
How to get a transaction fees?

### ISSUE THREAD

**Issue by awaik** [LtbLightning/bdk-flutter#58]
As we can see in the example with the package

`final PartiallySignedTransaction psbt = await txBuilder.addRecipient(script, 700).feeRate(1.1).finish(wallet);`

it was used as a predefined transaction fee.

Also, on the BDK website, there is an article https://bitcoindevkit.org/blog/2021/01/fee-estimation-for-light-clients-part-1/ about this issue.

So the question is - what is the recommended way to get fees for building a UX like in the attached image?

![photo_2023-02-13 12 07 35](https://user-images.githubusercontent.com/5330807/218388694-2087af61-de63-4454-af31-2e915ff2b746.jpeg)

**Comment by BitcoinZavior** [comment]
Hi @awaik enhanced fee estimation will be added to bdk-flutter in the next release. It will have flutter api for this functionality https://github.com/orgs/bitcoindevkit/projects/8?pane=issue&itemId=16803487
In the meantime electrs provides fee estimation:
link to fee estimate reference from electrs: https://github.com/blockstream/esplora/blob/master/API.md#get-fee-estimates
This is an example call to the blockstream public server for current fee rates:
https://blockstream.info/api/fee-estimates

**Comment by BitcoinZavior** [comment]
@awaik this is available in v0.27.1

**Comment by awaik** [comment]
> @awaik this is available in v0.27.1

Thank you! There are two issues:

1. I've tried to use it and always have a result 1.0 sat/vB. Code
`final FeeRate rate = await blockchain!.estimateFee(13);`

2. Even if I have correct sat/vB value, for example 15 sat/vB, I can't get a network fee in BTC. I'm trying to implement something like on the screenshot.

<img width="628" alt="Screenshot 2023-03-21 at 13 01 40" src="https://user-images.githubusercontent.com/5330807/226708696-2a04d9c1-e6dc-4073-a1a5-b1e6b17fb590.png">
