### ISSUE TITLE
Transaction feeRate

### ISSUE THREAD

**Issue by awaik** [LtbLightning/bdk-flutter#66]
In the example you used this code to built transaction

`PartiallySignedTransaction psbt =await txBuilder.addRecipient(script, 4000).feeRate(1,1).finish(wallet);`

Can you please explain, why you use `feeRate(1,1)`? 

I see in the code that this method receives

```
  ///Set a custom fee rate
  TxBuilder feeRate(double satPerVbyte) {
    _feeRate = satPerVbyte;
    return this;
  }
```

but satPerVbyte is an `int` value.

**Comment by BitcoinZavior** [comment]
Where is this from? Apologies I couldn't find it.

**Comment by awaik** [comment]
> Where is this from? Apologies I couldn't find it.

https://github.com/LtbLightning/bdk-flutter-quickstart/blob/3c6dc4e7438a8d15a1e4902b5dba2970e261fc34/lib/screens/home.dart#L106-L110

**Comment by BitcoinZavior** [comment]
It's `.feeRate(1.0)` so 1.0 is fine ` feeRate(double satPerVbyte)` accepts double type.

**Comment by awaik** [comment]
Yep, I can't find out what will be the fee in case I use `.feeRate(7.5)`
