### ISSUE TITLE
Can't sign multisig transaction.

### ISSUE THREAD

**Issue by awaik** [LtbLightning/bdk-flutter#84]
When I try to sign a multisig transaction I got an error `BdkException.unExpected(e: Unable to sign transaction)`

Here is a step-by-step explanation.

1. Create multisig wallet with descriptors:

external descriptor
`wsh(multi(2,[d7b36695/87'/0'/0']xpub...../0/*,[4006113c/87'/0'/0']xprv....../0/*))`
change
`wsh(multi(2,[d7b36695/87'/0'/0']xpub......./1/*,[4006113c/87'/0'/0']xprv......./1/*))`
create a wallet
```
    final wallet = await Wallet.create(
      descriptor: descriptor,
      changeDescriptor: change,
      network: Network.Bitcoin,
      databaseConfig: const DatabaseConfig.memory(),
    );
```

Wallet instantiated successfully can get the balance, utxos, & etc.

2. Create transaction:

- get all utxos, select utxos for trade
- get all txs
- cross-reference the utxos with the txs

```
      final Wallet walletFull = GetIt.I<AppParameters>().multisigWalletFull!;
      final List<LocalUtxo> utxos = await walletFull.listUnspent();
      final List<TransactionDetails> txs = await walletFull.listTransactions(true);
      final List<TransactionDetails> txsConfirmed = txs.where((e) => e.confirmationTime != null).toList();
      final List<LocalUtxo> utxosConfirmed =
          utxos.where((e) => txsConfirmed.firstWhereOrNull((val) => val.txid == e.outpoint.txid) != null).toList();
      final List<OutPoint> outpoints = [];
      for (final u in utxosConfirmed) {
        outpoints.add(u.outpoint);
      }
      List<String> assignedUtxosLst = outpoints.map((e) => '${e.txid}:${e.vout}').toList();
```

create tx

```
      final txBuilder = TxBuilder();
      final Address addressBobModel = await Address.create(address: bobAddress);
      final scriptBob = await addressBobModel.scriptPubKey();

      final Address addressAliceModel = await Address.create(address: aliceAddress);
      final scriptAlice= await addressAliceModel.scriptPubKey();

      final TxBuilderResult txBuilderResult = await txBuilder
          .addRecipient(scriptBob, toBobSatoshies)
          .addRecipient(scriptAlice, toAliceSatoshies)
          .feeRate(2.0)
          .manuallySelectedOnly()
          .addUtxos(utxos)
          .finish(wallet);
```

3. Sign transaction:

```
      final PartiallySignedTransaction signedTx = await wallet.sign(
        psbt: txBuilderResult.psbt,
        signOptions: const SignOptions(
            trustWitnessUtxo: true,
            allowAllSighashes: true,
            removePartialSigs: false,
            tryFinalize: false,
            signWithTapInternalKey: false,
            allowGrinding: false),
      );
```

On this step, I got the error `BdkException.unExpected(e: Unable to sign transaction)`

## How did I check that the transaction is correct?

I took the unsigned transaction from step 2 - `txBuilderResult` and got the raw unsigned (base64) psbt.

`final String psbtRaw = txBuilderResult.psbt.psbtBase64;`

After that, I opened Bitcoin Core wallet and applied these steps:

1. Open it (mainnet), go to file -> create wallet -> select descriptor wallet, blank wallet (dont disable private keys), give it a good name like "multisig-signer-for-testing"
2. go to window -> console
3. in the upper part of the console make sure Wallet: selected the correct walet (multisig-signer-for-testing)
4. Run this command to instantiate the same wallet as you have in the app:
`importdescriptors '[{"desc": "wsh(multi(2,[d7b36695/87'"'"'/0'"'"'/0'"'"']xpub...../0/*,[4006113c/87'"'"'/0'"'"'/0'"'"']xprv..../0/*))#gp6ggqtq", "active": true, "internal": false, "timestamp": 1677982769}, {"desc": "wsh(multi(2,[d7b36695/87'"'"'/0'"'"'/0'"'"']xpub..../1/*,[4006113c/87'"'"'/0'"'"'/0'"'"']xprv..../1/*))#pfj6qjha", "active": true, "internal": true, "timestamp": 1677982769}]'`
5. After that fired the `walletprocesspsbt` command and gave it the PSBT `psbtRaw`, and it was successfully signed it.

So PSBT is, in fact, correct.

## Plugin info

`  bdk_flutter: ^0.28.0`

Flutter doctor:

```
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.0.1 22A400 darwin-arm64, locale
    en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
[✓] VS Code (version 1.78.1)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!
```

**Comment by BitcoinZavior** [comment]
@awaik Thanks for identifying this issue. I was able to reproduce the bug and should have a fix shortly.
