### ISSUE TITLE
Error failed to run custom build command for `rust_bdk_ffi v0.29.0

### ISSUE THREAD

**Issue by hutomosaktikartiko** [LtbLightning/bdk-flutter#97]
I want to build this plugin for releasing my app with following [this](https://pub.dev/packages/bdk_flutter#how-to-build).
When I running this command 
```
cargo build
```
I found this error:
```
Error failed to run custom build command for `rust_bdk_ffi v0.29.0
```

**Comment by hutomosaktikartiko** [comment]
After searching, I thing the problem is using the wrong Flutter version when running this command. So I initialize the fvm (because I am using fvm). But I see the problem again. So I fixed this with set default flutter version for this project with added file settings.json at folder .vscode in root project (in here I am using vscode). This is my the code in settings.json
```
{
   "dart.flutterSdkPath": "/PATH_TO_FVM/fvm/versions/3.10.0",
}
    
```

**Comment by BitcoinZavior** [comment]
@hutomosaktikartiko Thanks for your interest.
Why do you want to build this?
To use the plugin in your app you can add from pub.dev building is not necessary.
